dist: xenial
language: node_js
node_js:
  - node
before_install:
  - $TRAVIS_BUILD_DIR/.travis/install_supercollider.sh
  - $TRAVIS_BUILD_DIR/.travis/install_supercolliderjs_config.sh
  - $TRAVIS_BUILD_DIR/.travis/install_quark.sh
  - sudo usermod -a -G audio $USER
  - sudo -E su $USER -c "groups"
  - echo $PATH
  - export NVM_CURRENT=$(nvm current)
  - echo $NVM_CURRENT
script: sudo -E su $USER -c "source $HOME/.nvm/nvm.sh; nvm current use $NVM_CURRENT; npm run test;"
cache:
  directories:
    - $HOME/supercollider
    - $HOME/sc3-plugins

