dist: xenial
language: node_js
node_js:
  - node
before_install:
  - $TRAVIS_BUILD_DIR/.travis/install_supercollider.sh
  - $TRAVIS_BUILD_DIR/.travis/install_supercolliderjs_config.sh
  - $TRAVIS_BUILD_DIR/.travis/install_quark.sh
  - which nvm
  - sudo usermod -a -G audio $USER
  - sudo -E -u $USER bash -c "groups"
script: sudo -E -u $USER bash -c "nvm current use $(nvm current); npm run test;"
cache:
  directories:
    - $HOME/supercollider
    - $HOME/sc3-plugins

