includePaths:
    -   /home/travis/.local/share/SuperCollider/downloaded-quarks/API
    -   /home/travis/.local/share/SuperCollider/downloaded-quarks/supercollider-redux
excludePaths:
    []
postInlineWarnings: false
